# Rogue presence-beacon throttle - SHARED, loaded by every PowerShell heartbeat.
#
#   . ([scriptblock]::Create((Get-Content -Raw -LiteralPath "$root\scripts\beacon.ps1")))
#   Initialize-RogueBeacon $creds
#   if (Request-RogueBeaconSlot -Slug 'claude' -Unthrottled $isSessionStart) { ... }
#
# ONE COPY IS EDITABLE: scripts/shared/beacon.ps1. Every plugin carries a
# byte-identical copy under plugins/<x>/scripts/, regenerated by
# scripts/sync-shared-scripts.sh and enforced by --check in CI. Editing a plugin's
# copy is silently reverted by the next sync. beacon.sh is the sh-side twin and the
# two must stay semantically identical - a machine's beacon cadence must not depend
# on its operating system. See beacon.sh for why this is shared at all.
#
# LOADED AS A SCRIPTBLOCK, never dot-sourced by path and never with -File: running
# a .ps1 file directly is subject to ExecutionPolicy and to a GPO-enforced policy
# that -ExecutionPolicy Bypass cannot override. Creating a scriptblock from the
# file's TEXT and dot-invoking it defines these functions in the caller's scope
# with no policy involved - the same trick hooks.json uses for the dispatchers.
#
# NOTHING RUNS AT LOAD TIME: this file only defines functions.

# The interval, as an int64. Defaulted here so a caller that never reaches
# Initialize-RogueBeacon (a damaged install, a test that only loads the library)
# still has a usable value rather than $null, which would compare as 0 and disable
# the throttle.
$script:rogueBeaconMinInterval = 900

# The interval is resolved from the CREDENTIAL MAP, not from $env: directly, and
# therefore only once the env files have been parsed - exactly like
# Initialize-Logging in the dispatchers, and for the same reason. Read at file
# scope, this silently ignores every env file: the sh heartbeats source them
# BEFORE reading the knob, so ROGUE_HEARTBEAT_MIN_INTERVAL in ~/.rogue-env or in an
# MDM C:\ProgramData\rogue\env would take effect on macOS and Linux and do nothing
# on Windows, leaving every Windows machine on the default. There is no workaround
# from a user's shell either: the heartbeats are spawned DETACHED, so their process
# environment comes from the coding agent, not from whoever configured the machine.
# Callers must also list the knob in their process-env override pass, so process
# env still wins over the files.
#
# A numeric zero DISABLES the throttle; a non-numeric value falls back to the
# default. Same rule as ROGUE_LOG_MAX_BYTES and ROGUE_SHIP_MIN_INTERVAL, so there
# is one convention to remember. On a per-turn trigger, zero means a beacon every
# turn: that is the knob doing what it says, and the default is what protects the
# fleet.
#
# TryParse, not a plain [int64] cast: the cast throws on a value too wide for the
# type, and while $ErrorActionPreference = 'SilentlyContinue' would swallow it and
# leave the default standing, that is the right answer reached by accident.
function Initialize-RogueBeacon {
    # [hashtable], defaulted: the merged credential map, whose precedence is
    # already correct by the time it gets here.
    param([hashtable]$Creds = @{})
    $script:rogueBeaconMinInterval = 900
    $raw = [string]$Creds['ROGUE_HEARTBEAT_MIN_INTERVAL']
    if (-not $raw) { return }
    $parsed = [int64]0
    if ([int64]::TryParse($raw, [ref]$parsed) -and $parsed -ge 0) {
        $script:rogueBeaconMinInterval = $parsed
    }
}

function Get-RogueBeaconUnixSeconds {
    # The epoch is CONSTRUCTED with DateTimeKind::Utc, never parsed from a string.
    # `[datetime]'1970-01-01T00:00:00Z'` looks equivalent and is not: .NET reads the
    # Z as UTC and then CONVERTS TO LOCAL, yielding Kind=Local
    # (1970-01-01T02:00+02:00 on a UTC+2 box). Subtracting a Local from a Utc does
    # naive tick arithmetic, so this returns epoch MINUS the machine's UTC offset.
    # The throttle still behaves correctly - one function both writes and reads the
    # stamp, so the delta is right - which is why only a test with an independent
    # reference clock catches it. What is wrong is the number on disk: hours off
    # from the true epoch beacon.sh writes to the same path with `date -u +%s`, and
    # from ship-logs.ps1's Get-EpochSeconds, which already does it this way.
    $epoch = New-Object DateTime(1970, 1, 1, 0, 0, 0, [DateTimeKind]::Utc)
    return [int64][Math]::Floor(((Get-Date).ToUniversalTime() - $epoch).TotalSeconds)
}

# Per-agent-family, under the ~/.rogue tree all six plugins share - so a machine
# running several coding agents throttles each family's beacon separately. The slug
# is a PARAMETER for the same reason it is one in ship-logs.ps1: nothing in here
# may derive a plugin's identity, and the families do not match the slugs anyway
# (codex ships under family `openai`).
#
# $HOME backs up USERPROFILE so this path also resolves when the library is loaded
# on macOS/Linux by the test suite.
function Get-RogueBeaconStampPath {
    param([string]$Slug)
    $beaconHome = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }
    return (Join-Path (Join-Path (Join-Path $beaconHome '.rogue') 'beacon') ".last-$Slug")
}

# Written BEFORE the request by Request-RogueBeaconSlot, which is what makes this a
# crash-loop guard as much as a rate limit: a beacon that hangs or dies still costs
# the next turn its attempt rather than retrying on every single one.
#
# There is no umask counterpart to beacon.sh's here, and that is not an omission:
# another standard user cannot read %USERPROFILE% to begin with.
function Set-RogueBeaconStamp {
    param([string]$Slug)
    try {
        $stamp = Get-RogueBeaconStampPath $Slug
        $dir = Split-Path -Parent $stamp
        if ($dir -and -not (Test-Path -LiteralPath $dir)) {
            New-Item -ItemType Directory -Path $dir -Force | Out-Null
        }
        # BOM-less UTF-8 and an LF, matching beacon.sh and the log writers:
        # Add-Content -Encoding UTF8 emits a BOM on Windows PowerShell 5.1 when it
        # creates the file, and the leading EF BB BF would then fail every TryParse
        # that reads it back - turning the throttle off permanently and silently
        # instead of noisily.
        [System.IO.File]::WriteAllText($stamp, "$(Get-RogueBeaconUnixSeconds)`n",
            (New-Object System.Text.UTF8Encoding $false))
    } catch { }
}

# $true = send this beacon (and the stamp has been written); $false = skip it.
# Deciding and stamping are ONE call on purpose: a caller that forgot the stamp
# would leave the window permanently open and the throttle would silently do
# nothing.
#
# -Unthrottled is $true for a session-start trigger and $false for a per-turn one.
# Which event names those are is the CALLER's business - the six plugins spell them
# SessionStart, sessionStart, AfterAgent, agentStop, stop and (Antigravity, which
# has no session event at all) the first PreInvocation of a turn. Taking a boolean
# instead of an event name keeps this library free of six vocabularies.
#
# A session-start trigger is NEVER throttled: it fires once per session, and a new
# session is exactly when the roster wants the update (a re-install with a new
# version, the same user on a different surface).
function Request-RogueBeaconSlot {
    param([string]$Slug, [bool]$Unthrottled = $false)

    if ($Unthrottled) { Set-RogueBeaconStamp $Slug; return $true }

    if ($script:rogueBeaconMinInterval -gt 0) {
        $stamp = Get-RogueBeaconStampPath $Slug
        # Every unreadable, corrupt, empty or FUTURE stamp answers "send". A stamp
        # we cannot trust must never be able to silence presence reporting - on the
        # roster that is indistinguishable from an uninstalled plugin.
        if (Test-Path -LiteralPath $stamp) {
            $raw = [string]((Get-Content -LiteralPath $stamp -TotalCount 1) -replace '\s', '')
            $last = [int64]0
            if ([int64]::TryParse($raw, [ref]$last)) {
                $now = Get-RogueBeaconUnixSeconds
                # A stamp in the FUTURE (clock stepped back, or a bad write) is
                # stale, not a reason to stay quiet until the clock catches up.
                if ($last -le $now -and ($now - $last) -lt $script:rogueBeaconMinInterval) {
                    return $false
                }
            }
        }
    }

    Set-RogueBeaconStamp $Slug
    return $true
}
